version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: runserver --elastic-url "http://elasticsearch:9200" --addr ":8080" --siteUrl $SITE_URL
    ports:
      - "80:8080"
    links:
      - elasticsearch

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    command: aggregate --elastic-url "http://elasticsearch:9200"
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    volumes:
      # https://github.com/docker-library/elasticsearch/issues/74
      - "/tmp/esdata:/usr/share/elasticsearch/data"
