version: '2'

services:
  app:
    build: .
    volumes:
     - .:/go/src/github.com/tomochikahara/rebuildfm-search
    ports:
      - "8080:8080"
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
